/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --env-interface CloudflareEnv worker/cloudflare-env.d.ts` (hash: 481f1eb16ffd5928c23e4af628cea8e4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		KVStore: KVNamespace;
		CROWDIN_CLIENT_ID: "{{CROWDIN_CLIENT_ID}}";
		CROWDIN_CLIENT_SECRET: "{{CROWDIN_CLIENT_SECRET}}";
		SCHEDULED_SECRET: "{{SCHEDULED_SECRET}}";
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CROWDIN_CLIENT_ID" | "CROWDIN_CLIENT_SECRET" | "SCHEDULED_SECRET">> {}
}
