/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts --include-runtime false` (hash: e669940878f54cd6928094f286f45e5e)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env {
		KVStore: KVNamespace;
		CROWDIN_CLIENT_ID: "{{CROWDIN_CLIENT_ID}}";
		CROWDIN_CLIENT_SECRET: "{{CROWDIN_CLIENT_SECRET}}";
		SCHEDULED_SECRET: "{{SCHEDULED_SECRET}}";
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CROWDIN_CLIENT_ID" | "CROWDIN_CLIENT_SECRET" | "SCHEDULED_SECRET">> {}
}
